In [328]:
import pandas as pd
from sklearn.model_selection import train_test_split
import numpy as np
import sklearn


In [329]:
df_diabetes = pd.read_csv("diabetes.csv")
np_diabetes = pd.DataFrame(df_diabetes).to_numpy()
train_set, test_set = train_test_split(my_df_loaded, test_size=0.2, random_state=42)

X_train = np.c_[train_set[["Pregnancies", "Glucose", "BloodPressure", "SkinThickness", "Insulin", "BMI", "DiabetesPedigreeFunction", "Age"]]]
y_train = np.c_[train_set["Outcome"]]
y_train = y_train.flatten()
y_train = 2 * y_train - 1

X_test = np.c_[test_set[["Pregnancies", "Glucose", "BloodPressure", "SkinThickness", "Insulin", "BMI", "DiabetesPedigreeFunction", "Age"]]]
y_test = np.c_[test_set["Outcome"]]
y_test = y_test.flatten()



In [330]:
def train_data(W,T,X_train,y_train,learning_rate):
    X_train = sklearn.preprocessing.normalize(X_train)
    X_train = np.c_[np.ones(len(X_train)), X_train]
    for j in range(T):
        step = np.zeros([len(X_train[0])])
        for i in range(len(X_train)):
            if y_train[i] * np.dot(X_train[i], W) <= 0:
                step += y_train[i] * X_train[i]
        W = W + learning_rate * step
    return W
    

In [331]:
def predict(x,W):
    x = np.c_[np.ones(len(x)), x]
    g = np.dot(x,W)
    s = np.sign(g)
    return s

In [332]:
W = np.zeros([len(X_train[0])+1])
W = train_data(W,1000,X_train, y_train, 0.001)
W

array([ 0.346     ,  0.59756894, -0.02879338, -1.04561699, -0.14188083,
       -0.18077804,  0.02113814,  0.01089822,  0.06782659])

In [333]:
y_predict = predict(X_train,W)
y_predict

array([ 1., -1., -1., -1., -1., -1.,  1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,  1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1.,  1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,  1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1.,  1., -1., -1., -1., -1., -1., -1.,  1., -1.,  1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
        1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1

In [334]:
np.count_nonzero(y_train == y_predict)/np.count_nonzero(y_train)

0.6416938110749185

In [335]:
y_predict = predict(X_test,W)
y_predict

array([-1., -1., -1., -1., -1., -1., -1.,  1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1.,  1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1.,  1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1.,  1.,  1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1.,  1., -1., -1., -1., -1.,
       -1., -1.,  1., -1., -1., -1., -1., -1., -1.,  1., -1.,  1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.])

In [336]:
np.count_nonzero(y_test == y_predict)/np.count_nonzero(y_test)

0.07272727272727272