In [403]:
import pandas as pd
from sklearn.model_selection import train_test_split
import numpy as np
import sklearn


In [404]:
df_diabetes = pd.read_csv("diabetes.csv")
np_diabetes = pd.DataFrame(df_diabetes).to_numpy()
train_set, test_set = train_test_split(my_df_loaded, test_size=0.2, random_state=42)

X_train = np.c_[train_set[["Pregnancies", "Glucose", "BloodPressure", "SkinThickness", "Insulin", "BMI", "DiabetesPedigreeFunction", "Age"]]]
y_train = np.c_[train_set["Outcome"]]
y_train = y_train.flatten()
y_train = 2 * y_train - 1

X_test = np.c_[test_set[["Pregnancies", "Glucose", "BloodPressure", "SkinThickness", "Insulin", "BMI", "DiabetesPedigreeFunction", "Age"]]]
y_test = np.c_[test_set["Outcome"]]
y_test = y_test.flatten()



In [405]:
X, y = load_svmlight_file('diabetes_scale')
X = np.array(X.todense())
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)


In [406]:
def train_data(W,T,X_train,y_train,learning_rate):
    X_train = sklearn.preprocessing.normalize(X_train)
    X_train = np.c_[np.ones(len(X_train)), X_train]
    for j in range(T):
        step = np.zeros([len(X_train[0])])
        for i in range(len(X_train)):
            if y_train[i] * np.dot(X_train[i], W) <= 0:
                step += y_train[i] * X_train[i]
        W = W + learning_rate * step
    return W
    

In [407]:
def predict(x,W):
    x = np.c_[np.ones(len(x)), x]
    g = np.dot(x,W)
    s = np.sign(g)
    return s

In [408]:
W = np.zeros([len(X_train[0])+1])
W = train_data(W,100,X_train, y_train, 0.001)
W

array([-0.052     , -0.06468086, -0.43062756,  0.03998113, -0.00110467,
        0.05182522, -0.33488619, -0.05346323, -0.11294551])

In [409]:
y_predict = predict(X_train,W)
y_predict

array([ 1., -1.,  1., -1.,  1.,  1., -1., -1.,  1.,  1.,  1.,  1., -1.,
        1.,  1., -1.,  1.,  1., -1., -1., -1.,  1.,  1., -1.,  1.,  1.,
        1., -1., -1., -1.,  1., -1., -1., -1.,  1., -1.,  1.,  1., -1.,
        1., -1.,  1.,  1., -1.,  1., -1.,  1., -1., -1.,  1.,  1.,  1.,
        1., -1.,  1.,  1.,  1., -1., -1.,  1., -1.,  1., -1.,  1.,  1.,
        1., -1., -1., -1.,  1.,  1., -1.,  1.,  1., -1.,  1.,  1.,  1.,
        1., -1.,  1.,  1., -1., -1.,  1.,  1., -1.,  1., -1., -1., -1.,
       -1.,  1.,  1.,  1., -1.,  1., -1., -1., -1., -1.,  1., -1., -1.,
        1., -1., -1., -1., -1., -1.,  1.,  1.,  1.,  1., -1., -1.,  1.,
        1., -1., -1., -1.,  1., -1., -1.,  1., -1., -1., -1., -1., -1.,
       -1.,  1., -1., -1.,  1.,  1., -1.,  1.,  1., -1., -1., -1., -1.,
       -1., -1., -1., -1.,  1.,  1.,  1.,  1.,  1., -1., -1., -1., -1.,
       -1.,  1., -1., -1.,  1., -1., -1.,  1., -1., -1.,  1., -1.,  1.,
        1.,  1.,  1., -1., -1., -1.,  1.,  1.,  1., -1., -1., -1

In [410]:
np.count_nonzero(y_train == y_predict)/np.count_nonzero(y_train)

0.7470817120622568

In [411]:
y_predict = predict(X_test,W)
y_predict

array([ 1.,  1.,  1.,  1., -1., -1.,  1., -1., -1., -1., -1., -1., -1.,
       -1.,  1., -1.,  1.,  1., -1., -1.,  1.,  1., -1.,  1., -1., -1.,
        1.,  1.,  1.,  1., -1., -1., -1., -1., -1., -1., -1.,  1., -1.,
       -1.,  1., -1., -1., -1.,  1., -1., -1.,  1., -1., -1.,  1., -1.,
       -1., -1.,  1.,  1., -1.,  1., -1., -1., -1., -1., -1.,  1.,  1.,
       -1.,  1., -1.,  1., -1., -1.,  1.,  1.,  1.,  1., -1.,  1.,  1.,
        1., -1., -1.,  1.,  1., -1.,  1., -1., -1., -1.,  1.,  1.,  1.,
        1.,  1., -1., -1., -1., -1.,  1., -1.,  1., -1.,  1., -1., -1.,
       -1.,  1., -1., -1.,  1., -1.,  1., -1.,  1., -1.,  1., -1., -1.,
        1.,  1., -1.,  1.,  1., -1.,  1., -1., -1.,  1., -1., -1., -1.,
       -1., -1.,  1., -1., -1.,  1.,  1., -1., -1.,  1.,  1.,  1., -1.,
       -1.,  1.,  1.,  1.,  1., -1., -1.,  1., -1., -1.,  1.,  1., -1.,
       -1., -1., -1.,  1., -1., -1.,  1.,  1.,  1., -1.,  1., -1., -1.,
       -1., -1.,  1., -1., -1., -1.,  1., -1., -1.,  1., -1., -1

In [412]:
np.count_nonzero(y_test == y_predict)/np.count_nonzero(y_test)

0.6653543307086615